##  Module 4–Introduction to NumPy, Pandas& Matplotlib

## Q1) Extract data from the givenSalaryGender CSV file and store the data from each column in a separate NumPy array

In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv(r'C:\Users\Rajan Kumar\Documents\Python_Sundog\DataScience\Python_Code_Rajan\574_m4_datasets_v3.0\SalaryGender.csv')


df.head()



Salary  Gender  Age  PhD
0   140.0       1   47    1
1    30.0       0   65    1
2    35.1       0   56    0
3    30.0       1   23    0
4    80.0       0   53    1

In [34]:
#extracting data in seperate file
sal_arr=np.array(df.Salary)
gen_arr=np.array(df.Gender)
age_arr=np.array(df.Age)
PhD_arr=np.array(df.PhD)

## Q2) The number of men with a PhD. The number of women with a PhD

In [95]:
df_PhD=df[df.PhD != 0]# without phd=0
print(df_PhD)
df_men_with_phd=df_PhD[df_PhD.Gender != 0]
print(df_men_with_phd.head())

df_women_with_phd=df_PhD[df_PhD.Gender != 1]
print(df_women_with_phd.head())

unique_elements,counts=np.unique(df_men_with_phd,return_counts=True)
print("number of men with a PhD", counts[0])

unique_elements,counts=np.unique(df_women_with_phd,return_counts=True)
print("number of women with a PhD", counts[0])

    Salary  Gender  Age  PhD
0    140.0       1   47    1
1     30.0       0   65    1
4     80.0       0   53    1
8    125.0       1   44    1
9     51.0       1   63    1
12   150.0       1   60    1
17    84.0       0   47    1
18   190.0       1   66    1
19    74.0       1   45    1
25    15.2       1   66    1
26    28.6       1   36    1
28    72.0       0   51    1
29    81.0       1   65    1
30   100.0       0   45    1
31    90.0       0   52    1
32    90.0       0   54    1
38    63.0       1   34    1
41    92.0       0   58    1
42   106.0       1   77    1
45    32.0       0   48    1
47    55.0       1   49    1
49    28.0       0   65    1
54    84.0       0   49    1
56   160.0       1   61    1
57    65.0       0   43    1
60   102.0       1   66    1
63    55.0       1   56    1
73   152.0       1   71    1
76    30.0       1   69    1
77   120.0       1   58    1
79    36.0       1   32    1
80    96.0       1   33    1
81    38.0       0   32    1
87    72.0    

## Q3 ) Use SalaryGender CSV file. Store the “Age” and “PhD” columns in one DataFrame and delete the data of all people who don’t have a PhD

In [89]:
print(df.head())
print("#"*30)
##dataFrame.iloc[<ROWS INDEX RANGE> , <COLUMNS INDEX RANGE>]
df_sal_gender=df.loc[:,['Age','PhD']]
print(df_sal_gender.head())
print("#"*30)
df_sal_gender1=df.iloc[:,[2,3]]
print("iloc -->",df_sal_gender1.head())

# Drop a row by condition
df_without_phd=df_sal_gender[df_sal_gender.PhD != 0]
print(df_without_phd.head())

   Salary  Gender  Age  PhD
0   140.0       1   47    1
1    30.0       0   65    1
2    35.1       0   56    0
3    30.0       1   23    0
4    80.0       0   53    1
##############################
   Age  PhD
0   47    1
1   65    1
2   56    0
3   23    0
4   53    1
##############################
iloc -->    Age  PhD
0   47    1
1   65    1
2   56    0
3   23    0
4   53    1
   Age  PhD
0   47    1
1   65    1
4   53    1
8   44    1
9   63    1


## 4.Calculate the total number of people who have a PhD degreefrom SalaryGender CSV file

In [99]:
unique_elements,counts=np.unique(df_PhD,return_counts=True)
print("Toal number of people having PhD", counts[1])

number of women with a PhD 63


## 5 ) How  do  you  Count  The  Number  Of  Times  Each  Value  Appears  In  An  Array  Of Integers?

In [102]:
arr=[0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]#Answer should be array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1])
arr1=np.array(arr)
print(arr1)

unique_elements,counts=np.unique(arr1,return_counts=True)

print(unique_elements,counts)


[0 5 4 0 4 4 3 0 0 5 2 1 1 9]
[0 1 2 3 4 5 9] [4 2 1 1 3 2 1]


## 6)Create a numpyarray [[0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9,10, 11]]) and filter the elements greater than 5

In [61]:
arr=np.array([[0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9,10, 11]])
print(arr)

print("Values bigger than 5 =", arr[arr>5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Values bigger than 5 = [ 6  7  8  9 10 11]


## 7)Create a numpy array having NaN (Not a Number) and print it.array([ nan,   1.,   2.,  nan,   3.,   4.,   5.])
--Print the same array omitting all elements which are nan

In [28]:
import numpy as np
x=["",1.,2.,"",4.,5.]
op=np.nan_to_num(x)
op


array(['', '1.0', '2.0', '', '4.0', '5.0'], dtype='<U3')


## 8.Create  a  10x10  array  with  random  values  and  find  the  minimum  and  maximum values

In [72]:
arr1=np.random.rand(10,10)
print("Original Array:")
print(arr1)
print("#"*50)
xmin, xmax = arr1.min(), arr1.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.57300743 0.48852218 0.20513883 0.95973968 0.66813987 0.88401423
  0.56291038 0.06394413 0.35739833 0.12595503]
 [0.09336324 0.74085366 0.06816192 0.86178645 0.97051012 0.31543044
  0.03419162 0.20873109 0.57600613 0.18866085]
 [0.51513894 0.05678112 0.756764   0.63555588 0.26130961 0.39160233
  0.43918113 0.37250671 0.7286319  0.2397192 ]
 [0.7221283  0.29324158 0.18269215 0.50196667 0.84599864 0.39936084
  0.37114512 0.9297341  0.96775806 0.39538703]
 [0.62729673 0.98914667 0.71116445 0.12687822 0.91253522 0.00344354
  0.2364936  0.02990644 0.65477404 0.89097116]
 [0.3116284  0.44355984 0.07740482 0.0353858  0.23953239 0.87268172
  0.28937764 0.64300021 0.41599061 0.83553064]
 [0.15676115 0.82747693 0.95146013 0.51712922 0.75977359 0.63109156
  0.79296495 0.52232818 0.06987919 0.40321358]
 [0.91767373 0.37534501 0.66834388 0.86740323 0.28552939 0.5904445
  0.41760728 0.62647299 0.5782759  0.05409778]
 [0.60996897 0.69030496 0.06423732 0.39946152 0.47003021 0.292645

 ##  9. Create a random vector of size 30 and find the mean value

In [77]:
x = np.random.rand(30)
print("Original vecgtor:")
print(x)
y=x.mean()
print("mean value:")
print(y)

Original vecgtor:
[0.5132015  0.74716062 0.41478493 0.2192202  0.48714582 0.15482459
 0.13938901 0.21494077 0.68227817 0.31147366 0.20230333 0.6715854
 0.79603242 0.67641003 0.27241688 0.51380942 0.36799965 0.42064686
 0.39415594 0.90077316 0.55571306 0.82041597 0.04766883 0.93495759
 0.44909175 0.53047831 0.01240537 0.24511432 0.59528248 0.59034195]
mean value:
0.46273406584826077


## 10.Create numpy array having elements 0 to 10 And negate all the elements between 3 and 9

In [95]:
arr10=np.arange(11)
print(arr10)

c=np.where((arr>3) & (arr<9) ,arr*-1,arr).flatten()

print(c)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11]


## 11.Create a random array of 3 rows and 3 columns and sort it according to 1stcolumn, 2ndcolumn or 3rdcolumn

In [104]:
arr3=np.arange(9).reshape(3,3)
print(arr3)
arr3[arr3[:,0].argsort()]
print("Result after sort :##################################")
print(arr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Result after sort :##################################
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 12.Create a four dimensions array get sum over the last two axis at once

In [108]:
arr4d=np.arange(16).reshape(4,4)
print(arr4d)
arr4d.sum(axis=(-1, -2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


120

## 13.Create a random array and swap two rows of an array.

In [113]:
a = np.random.randint(0, 10, (2, 3,3))
b = np.random.randint(0, 10, (2, 5,5))

print(a)

print("##################### printing b #############")
print(b)

#swap
a[:,0,0], b[:, 0, 0] = b[:, 0, 0], a[:, 0, 0].copy()

print("###################After swapping ########################33")
print(a)
print(b)


[[[0 7 9]
  [4 4 9]
  [5 4 0]]

 [[4 4 2]
  [4 2 9]
  [8 6 6]]]
##################### printing b #############
[[[5 4 1 9 6]
  [7 9 1 4 1]
  [1 7 6 5 7]
  [2 8 9 2 1]
  [1 7 9 2 3]]

 [[2 3 2 5 9]
  [9 7 9 4 4]
  [7 8 9 8 1]
  [5 5 8 4 7]
  [1 4 8 1 6]]]
###################After swapping ########################33
[[[5 7 9]
  [4 4 9]
  [5 4 0]]

 [[2 4 2]
  [4 2 9]
  [8 6 6]]]
[[[0 4 1 9 6]
  [7 9 1 4 1]
  [1 7 6 5 7]
  [2 8 9 2 1]
  [1 7 9 2 3]]

 [[4 3 2 5 9]
  [9 7 9 4 4]
  [7 8 9 8 1]
  [5 5 8 4 7]
  [1 4 8 1 6]]]


##   14.Create a randommatrix and Compute a matrix rank.

In [114]:
# Python 3 program to find rank of a matrix 
class rankMatrix(object): 
	def __init__(self, Matrix): 
		self.R = len(Matrix) 
		self.C = len(Matrix[0]) 
		
	# Function for exchanging two rows of a matrix 
	def swap(self, Matrix, row1, row2, col): 
		for i in range(col): 
			temp = Matrix[row1][i] 
			Matrix[row1][i] = Matrix[row2][i] 
			Matrix[row2][i] = temp 
			
	# Function to Display a matrix 
	def Display(self, Matrix, row, col): 
		for i in range(row): 
			for j in range(col): 
				print (" " + str(Matrix[i][j])) 
			print ('\n') 
			
	# Find rank of a matrix 
	def rankOfMatrix(self, Matrix): 
		rank = self.C 
		for row in range(0, rank, 1): 
			
			# Before we visit current row 
			# 'row', we make sure that 
			# mat[row][0],....mat[row][row-1] 
			# are 0. 
	
			# Diagonal element is not zero 
			if Matrix[row][row] != 0: 
				for col in range(0, self.R, 1): 
					if col != row: 
						
						# This makes all entries of current 
						# column as 0 except entry 'mat[row][row]' 
						multiplier = (Matrix[col][row] /
									Matrix[row][row]) 
						for i in range(rank): 
							Matrix[col][i] -= (multiplier *
											Matrix[row][i]) 
												
			# Diagonal element is already zero. 
			# Two cases arise: 
			# 1) If there is a row below it 
			# with non-zero entry, then swap 
			# this row with that row and process 
			# that row 
			# 2) If all elements in current 
			# column below mat[r][row] are 0, 
			# then remvoe this column by 
			# swapping it with last column and 
			# reducing number of columns by 1. 
			else: 
				reduce = True
				
				# Find the non-zero element 
				# in current column 
				for i in range(row + 1, self.R, 1): 
					
					# Swap the row with non-zero 
					# element with this row. 
					if Matrix[i][row] != 0: 
						self.swap(Matrix, row, i, rank) 
						reduce = False
						break
						
				# If we did not find any row with 
				# non-zero element in current 
				# columnm, then all values in 
				# this column are 0. 
				if reduce: 
					
					# Reduce number of columns 
					rank -= 1
					
					# copy the last column here 
					for i in range(0, self.R, 1): 
						Matrix[i][row] = Matrix[i][rank] 
						
				# process this row again 
				row -= 1
				
		# self.Display(Matrix, self.R,self.C) 
		return (rank) 

# Driver Code 
if __name__ == '__main__': 
	Matrix = [[10, 20, 10], 
			[-20, -30, 10], 
			[30, 50, 0]] 
	RankMatrix = rankMatrix(Matrix) 
	print ("Rank of the Matrix is:", 
		(RankMatrix.rankOfMatrix(Matrix))) 

# This code is contributed by Vikas Chitturi 


Rank of the Matrix is: 2


In [3]:
#15. C:\Users\Rajan Kumar\Documents\Python_Sundog\DataScience\Python_Code_Rajan\574_m4_datasets_v3.0
import pandas as pd

df=pd.read_csv(r'C:\Users\Rajan Kumar\Documents\Python_Sundog\DataScience\Python_Code_Rajan\574_m4_datasets_v3.0\middle_tn_schools.csv')

df.head()

name  school_rating   size  reduced_lunch  \
0  Allendale Elementary School            5.0  851.0           10.0   
1          Anderson Elementary            2.0  412.0           71.0   
2             Avoca Elementary            4.0  482.0           43.0   
3                Bailey Middle            0.0  394.0           91.0   
4          Barfield Elementary            4.0  948.0           26.0   

   state_percentile_16  state_percentile_15  stu_teach_ratio    school_type  \
0                 90.2                 95.8             15.7         Public   
1                 32.8                 37.3             12.8         Public   
2                 78.4                 83.6             16.6         Public   
3                  1.6                  1.0             13.1  Public Magnet   
4                 85.3                 89.2             14.8         Public   

   avg_score_15  avg_score_16  full_time_teachers  percent_black  \
0          89.4          85.2                54.0            2.9   
1          43.0          38.3                32.0            3.9   
2          75.7          73.0                29.0            1.0   
3           2.1           4.4                30.0           80.7   
4          81.3          79.6                64.0           11.8   

   percent_white  percent_asian  percent_hispanic  
0           85.5            1.6               5.6  
1           86.7            1.0               4.9  
2           91.5            1.2               4.4  
3           11.7            2.3               4.3  
4           71.2            7.1               6.0

In [119]:

df.describe()

school_rating         size  reduced_lunch  state_percentile_16  \
count     347.000000   347.000000     347.000000           347.000000   
mean        2.968300   699.472622      50.279539            58.801729   
std         1.690377   400.598636      25.480236            32.540747   
min         0.000000    53.000000       2.000000             0.200000   
25%         2.000000   420.500000      30.000000            30.950000   
50%         3.000000   595.000000      51.000000            66.400000   
75%         4.000000   851.000000      71.500000            88.000000   
max         5.000000  2314.000000      98.000000            99.800000   

       state_percentile_15  stu_teach_ratio  avg_score_15  avg_score_16  \
count           341.000000       347.000000    341.000000    347.000000   
mean             58.249267        15.461671     57.004692     57.049856   
std              32.702630         5.725170     26.696450     27.968974   
min               0.600000         4.700000      1.500000      0.100000   
25%              27.100000        13.700000     37.600000     37.000000   
50%              65.800000        15.000000     61.800000     60.700000   
75%              88.600000        16.700000     79.600000     80.250000   
max              99.800000       111.000000     99.000000     98.900000   

       full_time_teachers  percent_black  percent_white  percent_asian  \
count          347.000000     347.000000     347.000000     347.000000   
mean            44.939481      21.197983      61.673487       2.642651   
std             22.053386      23.562538      27.274859       3.109629   
min              2.000000       0.000000       1.100000       0.000000   
25%             30.000000       3.600000      40.600000       0.750000   
50%             40.000000      13.500000      68.700000       1.600000   
75%             54.000000      28.350000      85.950000       3.100000   
max            140.000000      97.400000      99.700000      21.100000   

       percent_hispanic  
count        347.000000  
mean          11.164553  
std           12.030608  
min            0.000000  
25%            3.800000  
50%            6.400000  
75%           13.800000  
max           65.200000

In [9]:
team_rating=df.groupby(['school_rating'])
team_rating